name: dtraleigh_opal_v2
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - expat=2.6.3=h5da7b33_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py312haa95532_0
  - python=3.12.7=h14ffc60_0
  - setuptools=75.1.0=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - wheel=0.44.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - arcgis2geojson==3.0.3
      - asgiref==3.8.1
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - django==5.1.3
      - django-debug-toolbar==4.4.6
      - django-environ==0.11.2
      - django-extensions==3.2.3
      - django-leaflet==0.31.0
      - django-simple-history==3.7.0
      - django-tables2==2.7.0
      - django-widget-tweaks==1.5.0
      - fuzzywuzzy==0.18.0
      - geographiclib==2.0
      - geojson==3.1.0
      - geopandas==1.0.1
      - geopy==2.4.1
      - idna==3.10
      - levenshtein==0.26.1
      - numpy==2.1.3
      - packaging==24.1
      - pandas==2.2.3
      - prettytable==3.12.0
      - psycopg2-binary==2.9.10
      - pyogrio==0.10.0
      - pyproj==3.7.0
      - python-dateutil==2.9.0.post0
      - python-levenshtein==0.26.1
      - pytz==2024.2
      - rapidfuzz==3.10.1
      - requests==2.32.3
      - shapely==2.0.6
      - six==1.16.0
      - soupsieve==2.6
      - sqlparse==0.5.1
      - tzdata==2024.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
prefix: C:\Users\leo\miniconda3.12\envs\dtraleigh_opal_v2
